-- Tests that `rewrite` inside a --postfix-methods copattern clause works.
--
-- Regression: commit 5624e7c0ef introduced PostfixProjP in A.Pattern to
-- defer field resolution to splitRest.  The with-clause generated by
-- `rewrite` carried the unresolved PostfixProjP into stripWithClausePatterns,
-- where A.isProjP PostfixProjP{} = Nothing caused a spurious
-- WithClausePatternMismatch error.
--
-- Fix: in With.hs strip, accept PostfixProjP when the internal pattern is
-- ProjP (the parent clause already verified the match).

{-# OPTIONS --postfix-methods #-}
module PostfixMethodsRewrite where

open import Agda.Builtin.Equality

record HasOp (A : Set) : Set where
  field op : A → A → A

open HasOp

-- rewrite inside a postfix copattern clause (non-reflexive)
NatRefl : {A : Set} (a : A) → HasOp A
NatRefl a .op x y rewrite (refl {x = x}) = y

record HasSym (A : Set) : Set where
  field sym : {x y : A} → x ≡ y → y ≡ x

open HasSym

-- rewrite on an implicit pattern inside a copattern clause
trivSym : {A : Set} → HasSym A
trivSym .sym {x} {y} p rewrite p = refl
